### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by bolonio** [r7kamura/rubocop-extension-template#1]
Hi @r7kamura,

Can you add a license file to your repo?

You can read more in the [documentation about Licensing a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) or you can see an [example in the Hubot repository](https://github.com/hubotio/hubot/blob/master/LICENSE.md).

Thanks :)

**Comment by r7kamura** [comment]
Hi @bolonio, thanks for creating the isssue.

I'd like to license this template under the MIT license, but I don't think I can solve this problem by putting the file there like a normal repository. If I put LICENSE file with something like "Copyright (c) 2022 r7kamura" in this type of template repository, the LICENSE file will be copied to the repository created from this template, which I think is kind of strange.

I wonder how other template repositories are solving this problem?

**Comment by bolonio** [comment]
> I'd like to license this template under the MIT license, but I don't think I can solve this problem by putting the file there like a normal repository. If I put LICENSE file with something like "Copyright (c) 2022 r7kamura" in this type of template repository, the LICENSE file will be copied to the repository created from this template, which I think is kind of strange.
> 
> I wonder how other template repositories are solving this problem?

@r7kamura  Great point, how about adding the license info in the README?

**Comment by r7kamura** [comment]
> @r7kamura Great point, how about adding the license info in the README?

Fair enough. I'll add it to README 👍
